### ISSUE TITLE
整理需求

### ISSUE THREAD

**Issue by emeryao** [jyma1991/Nail#2]
需求格式如下：
- [ ] 添加会员
- [ ] 查询会员信息
- [ ] 修改会员信息
- [ ] 等等

**Comment by Emeryao** [comment]
需求格式如下：
- [ ] 添加会员
- [ ] 查询会员信息
- [ ] 修改会员信息
- [ ] 等等

**Comment by jyma1991** [comment]
- [ ] 账户类型有两种 一种为金额，一种为次卡类型，录入时记录为次数，消费则减
- [ ] 流水展示  参考
  ![image](https://cloud.githubusercontent.com/assets/12162665/19220621/1c3a7e0a-8e64-11e6-94eb-6302ae7e3378.png)
